export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header 
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>Headers</p>
        </header>

        {children}

        <footer 
          style={{
            backgroundColor: "lightgray",
            padding: "1rem",
          }}>
          <p>Footers</p>
        </footer>

      </body>
    </html>
  )
}
